name: 更新文档

env:
  # 输入仓库名
  INPUT_WAREHOUSE_NAME: MKFramework
  # 输入路径
  INPUT_PATH: tool/api-extractor/docs/mk
  # 输出仓库名
  OUTPUT_WAREHOUSE_NAME: 1226085293.github.io
  # 输出路径
  OUTPUT_PATH: src/MK框架/API 接口/mk

on:
  push:
    branches: [dev]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 1226085293/${{ env.INPUT_WAREHOUSE_NAME }}
          fetch-depth: 0

      - name: 设置用户名和邮箱
        run: |
          git config --global user.name "muzzik"
          git config --global user.email "1226085293@qq.com"

      - name: 构建框架文档
        run: |
          cd tool/api-extractor
          npm install
          npm run 构建框架文档

      - name: 清空输出目录
        run: |
          git clone https://github.com/1226085293/${{ env.OUTPUT_WAREHOUSE_NAME }}.git
          cd ${{ env.OUTPUT_WAREHOUSE_NAME }}
          if [ -d "${{ env.OUTPUT_PATH }}" ]; then
            rm -rf "${{ env.OUTPUT_PATH }}"
          fi
  
      - name: 创建输出目录
        run: |
          cd ${{ env.OUTPUT_WAREHOUSE_NAME }}
          mkdir -p "${{ env.OUTPUT_PATH }}"

      - name: 拷贝文件到输出仓库
        run: |
          cp -R "../${{ env.INPUT_WAREHOUSE_NAME }}/${{ env.INPUT_PATH }}/." "./${{ env.OUTPUT_WAREHOUSE_NAME }}/${{ env.OUTPUT_PATH }}"

      - name: 推送到输出仓库
        if: steps.check_changes.outputs.changes
        run: |
          cd ${{ env.OUTPUT_WAREHOUSE_NAME }}
          git add .
          git commit -m "更新 MK 框架 API 文档"
          git push --force https://${{ secrets.ACCESS_TOKEN }}@github.com/1226085293/${{ env.OUTPUT_WAREHOUSE_NAME }}.git