name: 更新文档

on:
  push:
    branches: [dev]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 1226085293/MKFramework
          fetch-depth: 0

      - name: Install dependencies and build framework docs
        run: |
          cd tool/api-extractor
          npm install
          npm run 构建框架文档

      - name: Remove existing tool/docs folder in repository B
        run: |
          git config --local user.name "muzzik"
          git config --local user.email "1226085293@qq.com"
          git clone https://github.com/1226085293/test.git # 替换为仓库B的用户名和仓库名
          cd test
          rm -rf tool/docs
  
      - name: Create tool/docs directory in repository B
        run: |
          cd test
          mkdir -p tool/docs

      - name: Copy docs folder from repository A to repository B
        run: |
          cp -R ../MKFramework/tool/api-extractor/docs ./test/tool/docs
  
      - name: List files in tool/docs directory
        run: |
          ls -R test/tool/docs

      - name: Commit and push changes to repository B
        run: |
          cd test
          git config --local user.name "muzzik"
          git config --local user.email "1226085293@qq.com"
          git add .
          git commit -m "Update Docs"
          git push